name = "ScaleInvariantAnalysis"
uuid = "727e6139-ff52-4636-a344-ed1d23e73ffc"
version = "1.0.0-DEV"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]

[deps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PrimalDualLinearAlgebra = "398bc1fc-7a5b-4dd0-a759-e1c0ad42bb90"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DifferentiationInterface = "0.7"
ForwardDiff = "1"
LinearAlgebra = "1.10.0"
SparseArrays = "1.10.0"
julia = "1.10.10"

[extras]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DifferentiationInterface", "ForwardDiff", "Test"]
